version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3001:3001
    env_file:
      - ./.env.docker

  my-database:
    image: postgres:15-alpine # mysql → postgres:15-alpine
    environment:
      POSTGRES_DB: "mydocker" # MYSQL_DATABASE → POSTGRES_DB
      POSTGRES_USER: "postgres" # 추가
      POSTGRES_PASSWORD: "june1508!!" # MYSQL_ROOT_PASSWORD → POSTGRES_PASSWORD
    ports:
      - 5432:5432 # 3306 → 5432

  my-redis:
    image: redis:latest
    ports:
      - 6379:6379
